[build-system]
requires = ["setuptools", "build"]

[project]
name = "hexdump.py"
authors = [
    {name = "D. St.", email = "dan.stonewall@gmail.com"}
]
dynamic = ["version"]

[project.scripts]
hexdump = "hexdump.__main__:main"
